### ISSUE TITLE
api.get_homes(lat, lng) does not work

### ISSUE THREAD

**Issue by DmitriyG228** [nderkach/airbnb-python#10]
latitude, longitude for get_homes returns some random listings around the world

**Comment by jaksmid** [comment]
confirmed, seems like the API was changed.

I could manage to get the rectangle on the map working determined by two pairs of coordinates (parameters `ne_lat`, `ne_lng`, `sw_lat`, `sw_lng`) but not just a single pair of coordinate. Will create a PR if I figure it out

**Comment by nderkach** [comment]
Would be nice to add some tests for API responses at some point 🤔
