### ISSUE TITLE
get listing details stopped working

### ISSUE THREAD

**Issue by fedebenji** [nderkach/airbnb-python#24]
Hello,
I get this error on get listing details (I've covered the listing ID on purpose):

400 Client Error: Bad Request for url: https://api.airbnb.com/v2/pdp_listing_details/XXXXXXX?adults=0&_format=for_native&infants=0&children=0

Thanks

Federico

**Comment by eladhayun** [comment]
Same here, anyone knows the new endpoint?

**Comment by remybar** [comment]
But is there a new endpoint ? I saw in other projects that now there is an API v3 using GraphQL ... :(

**Comment by fedebenji** [comment]
I found the solution, the API KEY provided in the code stopped working. That's why. You have to change it with the one you find in your browser requests details (dev mode).

**Comment by eladhayun-rep-holdings** [comment]
@fedebenji can you please elaborate on how did you get the token?
the /authenticate API returns a cookie with sparse data in it

**Comment by kingfisher429** [comment]
+1 on the request to elaborate

**Comment by remybar** [comment]
Just access to an airbnb page, on your web browser dev tools and search for `api/v2` calls. You will find an request parameter called `key`. That's the key to use instead of your current one that is broken now.

**Comment by fedebenji** [comment]
@eladhayun-rep-holdings, @kingfisher429 
Just as @remybar wrote:

1. open your browser's developer tools tab, network section, XHR
2. navigate to an Airbnb.com page 
2. look for GET API calls (v2 or v3) -> Header -> Request Header ->Airbnb API Key

**Comment by assaf13** [comment]
Thanks @fedebenji 
I am still getting the same error even after updating the airbnb_access_token with the Airbnb API Key that I found at the Request Header.
Did you able to call get_listing_details api or alternatively call the rest API directly ?
can you send an example ?

**Comment by greeceruit** [comment]
Hello! Is there any news on the topic? Maybe someone found another API (or library)?

**Comment by mcglocks5051** [comment]
+1 on the above comments. Got the new API key, but still getting the 420 message.

**Comment by r3v3r3seEntropy** [comment]
i am still not able to fix this
