### ISSUE TITLE
Number of guests

### ISSUE THREAD

**Issue by gianlucaromito** [nderkach/airbnb-python#4]
Hello. First of all... very nice work! It is something I was searching and you made it :)
Now the question... is there a way I can have, from the api.get_calendar, the number of guests that have reserved my room? I see that the calendar rerturns me some info about if a certain date is available or not but not about the number of guests that are coming.
Thanks very much for your help/support!

Gianluca

**Comment by nderkach** [comment]
`get_calendar` returns just the information available to the guests, so on their side, they just know if certain dates are available or not for a listing.

Unfortunately, I don't have an Airbnb host account to reverse-engineer those API requests. Out of curiosity, why do you need the information about the number of guests through the API?

**Comment by gianlucaromito** [comment]
Now it is clear to me... I tried to make a small python script to get this info so I can pass it to the cleaning service. So they know how many items like coffe and breakfast they should prepare :) I've asked to airbnb to have a host account (https://www.airbnb.it/partner) but they have never answered to me.

**Comment by nderkach** [comment]
I've played a bit with a host profile, and found a way to get a listing calendar which might contain the data your are looking for (since I have no live reservations, it would be difficult to verify). Check out `api.get_listing_calendar()` with your listing id.

**Comment by gianlucaromito** [comment]
I will try... now I'm getting the VerificationError like https://github.com/nderkach/airbnb-python/issues/3
Is it possible to get the Api(access_token=<token>) from the "web page" after a successfull login?

**Comment by nderkach** [comment]
The web app appears to use a different authentication flow. To be honest I don't know a consistent way to bypass the verification error. I'd recommend setting up a MITM proxy and intercept the app requests yourself, for example following [this tutorial](https://www.toptal.com/back-end/reverse-engineering-the-private-api-hacking-your-couch). Thankfully, it's pretty straightforward to do with Airbnb's mobile apps.

**Comment by Patrick3131** [comment]
@gianlucaromito did you figure out how to get the number of guests from airbnb?

**Comment by gianlucaromito** [comment]
No. but I'm trying to use the "export calendar" feature of airbnb and read
it via python. It seems that the info is "hidden" inside the ics file...
work in progress :)

Il lun 25 giu 2018, 21:56 Patrick3131 <notifications@github.com> ha scritto:

**Comment by Patrick3131** [comment]
My current solution is, that I add the number of guests as a note to the calendar. Then the guest information can also be seen via ical link by the cleaning company.

**Comment by gianlucaromito** [comment]
Yes that should work. Great idea! Hopefully they give an API to get that
info too. I've the same thing with Booking.com...

Il mar 26 giu 2018, 09:12 Patrick3131 <notifications@github.com> ha scritto:

**Comment by nderkach** [comment]
Since I don't have a host account on Airbnb, I'm gonna close this issue for now. Would be happy to reverse-engineer it otherwise :)
