### ISSUE TITLE
feature request: get payout for each guest on the calendar

### ISSUE THREAD

**Issue by ec1oud** [nderkach/airbnb-python#8]
Now that they have stopped taking care of payouts to my cohost (quite some months ago now), I have to do some manual calculations periodically (once a month or so) to give him his commission plus the cleaning fee.  I keep a log to keep track of which guests I've paid him for.  So I'd like to script this.

Do we know how to get the payout amount from the API?

**Comment by nderkach** [comment]
@ec1oud Unfortunately, I don't have a host account with Airbnb, so I can't reverse-engineer that path.
Hopefully, someone eventually would be so generous to contribute host account credentials for testing :)

**Comment by elmcrest** [comment]
@nderkach we could discuss the host account credentials if it would help... obviously I can't have public credentials.

from playing with your Api, related to above question I think:
```python
>>> authenticated_api.get_listing(12345678)['calendar']['days'][10]['reservation']['host_payout_formatted']
'€450.33'
```
thx for the great work btw nderkach ;)
